### ISSUE TITLE
Audio player element is missing from Phonograph component

### ISSUE THREAD

**Issue by franknoirot** [netamorphosis/lg-wedding#1]
I made this issue on my **phone** while walking to get coffee. Sick!

**Comment by robpetrin** [comment]
I want in on this one!

**Comment by franknoirot** [comment]
Dang it @robpetrin I'm sorry I missed these comments it looks like I don't get notifications on discussions until I'm directly tagged in a comment, even if I start them?

**Comment by robpetrin** [comment]
Haha well I have the opposite problem and I got notifications for every beat-by-beat on this @franknoirot
