### ISSUE TITLE
Complete /wedding page

### ISSUE THREAD

**Issue by franknoirot** [netamorphosis/lg-wedding#14]
Following [these designs in Figma](https://www.figma.com/proto/lQ7CjNpS2EoFp27o3xR2WI/Concepts-and-Wireframes?page-id=78%3A1121&node-id=80%3A1357&viewport=-61%2C301%2C0.2714636027812958&scaling=min-zoom)

**Comment by robpetrin** [comment]
All set, pending responsive (its own issue).
