### ISSUE TITLE
Add in Nav Links

### ISSUE THREAD

**Issue by franknoirot** [netamorphosis/lg-wedding#2]
Be sure to include the rollover state SVG as shown in the [Figma designs](https://www.figma.com/proto/lQ7CjNpS2EoFp27o3xR2WI/Concepts-and-Wireframes?page-id=62%3A693&node-id=62%3A694&viewport=1204%2C1833%2C1.7764865159988403&scaling=min-zoom)

**Comment by franknoirot** [comment]
@robpetrin deploy preview link for this PR: https://60f7314efc11110007d62c81--lg-wedding.netlify.app/

Trying toggling the phonograph player and changing pages!

**Comment by robpetrin** [comment]
Nice! Can confirm this works. Do deploy previews persist indefinitely?

**Comment by franknoirot** [comment]
> Nice! Can confirm this works. Do deploy previews persist indefinitely?

Yup yup, might go away after the PR closes but I can't confirm.

**Comment by robpetrin** [comment]
Closed via PR #3
