### ISSUE TITLE
iOS no audio playback when phonogram activated

### ISSUE THREAD

**Issue by robpetrin** [netamorphosis/lg-wedding#34]
Getting mixed results in Safari, but no audio is playing back in iOS period. :(

**Comment by robpetrin** [comment]
Break in the case (without resolution) -- you can run localhost in Simulator to test this live. It'll actually throw a Next.JS error when you try to do it on an iOS device.

![image](https://user-images.githubusercontent.com/20173621/127400332-df452b7a-573b-494b-970c-537a00c70292.png)

I believe it's because you're not explicitly clicking play on the audio element itself (and the wrapping button doesn't suffice). 🤔

**Comment by franknoirot** [comment]
@robpetrin I've confirmed that this has to due with Safari permissions around audio playback. Adding the `controls` parameter to the `<audio>` element (which makes the player element visible) allows me to click play/pause on the audio. Looking for a way of triggering audio playback that meets Safari's guidelines on user interaction.
