### ISSUE TITLE
Autoplay audio support?

### ISSUE THREAD

**Issue by robpetrin** [netamorphosis/lg-wedding#36]
Let's TB on audio autoplay -- LS would like this but I think it's a security no-no (at least in Chrome). I can update state/toggle for this (and added autoplay attribute onto the tag), but no actual audio plays.

**Comment by franknoirot** [comment]
@robpetrin you are correct, as of 2017 Chrome stopped respecting the `autoplay` attribute and all browsers have similar policies. Here is the Chrome Dev Team's [primary article on autoplay best practice](https://developer.chrome.com/blog/autoplay/#new-behaviors), and within it is stated that audio simply won't play in Chrome without some interaction or pre-existing permission from the user. While I have found hacky ways of spoofing playback used by web game developers, I don't think it is worth getting in the habit of reaching for solutions like that, as they are unreliable at best and are widely considered antipatterns.

Closing as unable to fix.
