### ISSUE TITLE
Phonograph toggle resets when you switch pages

### ISSUE THREAD

**Issue by franknoirot** [netamorphosis/lg-wedding#4]
Need some kind of global context to keep that state across pages.

**Comment by robpetrin** [comment]
Do we localize this prop to the nav item which will be present on all pages, or is there a better way to go about implementing this prop?

**Comment by robpetrin** [comment]
nvm you fixed this!

**Comment by franknoirot** [comment]
@robpetrin sorry I missed your message! Yeah I used a custom `useContext` hook within the `_app.js` file.
