### ISSUE TITLE
Set up prettier to add a newline at the end of each file

### ISSUE THREAD

**Issue by robpetrin** [netamorphosis/lg-wedding#5]
We need a check to ensure each file ends with a blanked line. We're getting warnings in our PRs for these --

![image](https://user-images.githubusercontent.com/20173621/126504929-459b53ec-a9b3-4f42-ab1d-1ce6047cb84e.png)

**Comment by franknoirot** [comment]
@robpetrin I'm wondering if this is because I missed running `npm run lint` before pushing? Still trying to figure it out.

**Comment by robpetrin** [comment]
We got this nearly simultaneously -- next step is making it automatically fix it when it finds this one, but warnings work for now!
