### ISSUE TITLE
Create an auto-rotating Carousel component

### ISSUE THREAD

**Issue by franknoirot** [netamorphosis/lg-wedding#6]
## Designs
Made in [Figma design space](https://www.figma.com/file/lQ7CjNpS2EoFp27o3xR2WI/Concepts-and-Wireframes?node-id=62%3A694)

## Requirements
- Must contain all images sizes to the same height in a row
- Must auto-scroll (or rotate) across the page by default, and return to the start seamlessly
- Must be able to manually scroll if the user wants by clicking/tapping and dragging.
  - Auto-scroll may stop after manual scroll if UX is difficult to restart it.

**Comment by franknoirot** [comment]
@robpetrin if you'd like to  there's this npm package [infinite-react-carousel](https://www.npmjs.com/package/infinite-react-carousel) and try integrating it as an exercise that would be great.

If you instead want to take a stab at coding your own Carousel component as an exercise I think [this chapter on Content Sliders](https://inclusive-components.design/a-content-slider/) from Heydon Pickering's book _Inclusive Components_, in combination with [this blog post](https://medium.com/@RahulTMody/create-a-scrolling-image-slider-in-react-1e4eddcd407b) by Rahul Mody will be helpful.

**Comment by franknoirot** [comment]
As of PR #11 Rob is developing this feature using the `react-slick` package.

**Comment by robpetrin** [comment]
**Update here: ** Through the magic of teamwork, the slider is semi-functional. Some issues --
* It is not yet responsive
* It doesn't paginate elegantly (assumes uniform width, so it half-paginates and over-paginates)
* It needs to come out of the main page flow. Achievable via absolute positioning hopefully!

Still on it -- thanks @franknoirot

**Comment by robpetrin** [comment]
Closing this bad boy up
